'use strict';
const assert=require('node:assert/strict');global.window=global;require('../data/game-data-bundle.js');const E=require('../data/game-engine.js'),B=require('../js/board.js'),cards=GAME_SOURCE_BUNDLE.sources.map(c=>E.derive(c));
function session(id,rolls=[1],role='characters-009'){const s=new E.play.Session(cards,B,()=>0);s.start('骰子測試',role);let index=0;s.rng=()=>((rolls[index++%rolls.length])-1)/6;s.active.cash=1000000;s.state.phase='resolving';s.state.pending={kind:'card',cardId:id,tileId:'taiwan-2'};return s;}
for(const die of [1,2,3,4,5,6]){
 const s=session('investment-opportunity-001',[die]);assert.throws(()=>s.rollEventDie());assert.equal(s.active.cash,1000000);s.acceptDice();assert.equal(s.active.cash,900000);assert.throws(()=>s.acceptDice());assert.throws(()=>s.skip());
 const r=new E.play.Session(cards,B,()=> (die-1)/6,s.state);r.rollEventDie();assert.equal(r.active.cash,die===1?1100000:900000);assert.throws(()=>r.rollEventDie());const saved=new E.play.Session(cards,B,()=>0,r.state);assert.throws(()=>saved.rollEventDie());saved.apply();assert.equal(saved.active.cash,die===1?1100000:900000);assert.equal(saved.state.events.filter(e=>e.code==='DICE_RESULT').length,1);const log=saved.state.events.find(e=>e.code==='DICE_RESULT');assert.equal(log.cardName,'投資新型虛擬貨幣');assert.equal(log.diceCount,1);assert.deepEqual(log.rolls,[die]);assert.equal(log.changes.cash,die===1?200000:0);
}
const poor=session('investment-opportunity-001');poor.active.cash=99999;assert.throws(()=>poor.acceptDice());assert.throws(()=>poor.rollEventDie());poor.skip();assert.equal(poor.active.cash,99999);
for(const source of cards){const c=E.play.upgradeCard(source);if(!/骰/.test(c.effective?.effect||'')||c.category==='角色')continue;assert.ok(c.resolver?.dice,c.cardId+' needs a dice resolver');for(const die of [1,6]){const s=session(c.cardId,[die]);if(s.preview().waitingDecision)s.acceptDice();while(s.preview().waitingDice)s.rollEventDie();s.apply();assert.equal(s.state.phase,'done');assert.ok(s.state.events.some(e=>e.code==='DICE_RESULT'),c.cardId);}}
for(let a=1;a<=6;a++)for(let b=1;b<=6;b++){const s=session('daily-life-059',[a,b]);s.rollEventDie();assert.throws(()=>s.apply());s.rollEventDie();assert.throws(()=>s.rollEventDie());s.apply();assert.equal(s.active.cash,1000000-(a+b)*1000);}
for(let a=1;a<=6;a++)for(let b=1;b<=6;b++)for(let c=1;c<=6;c++){const s=session('daily-life-075',[a,b,c]);s.acceptDice();s.rollEventDie();s.rollEventDie();assert.throws(()=>s.apply());s.rollEventDie();const sum=a+b+c;assert.equal(s.active.cash,999000+(sum===3?1000000:sum<=8?10000:sum<=12?500:0));s.apply();}
for(const die of [1,6]){const s=session('daily-life-020',[die]);s.rollEventDie();assert.equal(s.active.cash,1000000);assert.equal(s.active.debtTotal,die===1?300000:200000);assert.equal(s.active.loanInterest,0);s.apply();}
const transfer=session('investment-opportunity-002',[6]);transfer.acceptDice(1);const cash=transfer.state.players[1].cash;transfer.rollEventDie();assert.equal(transfer.state.players[1].cash,cash-20000);assert.equal(transfer.active.cash,1000000);transfer.apply();
for(const die of [1,6])for(const id of ['real-estate-suburban-029','real-estate-suburban-031']){
 const s=session(id,[die]);s.active.assets.properties=[{id:'house',cardId:'real-estate-city-002',name:'郊區透天',purchasePrice:8000000,value:9000000,cost:2400000,income:18000,units:1}];s.active.liabilities.mortgage=[{id:'house',principal:5600000,monthlyPayment:12000}];E.play.calculate(s.active);
 if(s.preview().waitingDecision)s.acceptDice();s.rollEventDie();assert.ok(s.preview().salePending);const factor=id==='real-estate-suburban-029'?(die===1?1.2:1.5):(die===1?.7:.5);s.apply();assert.equal(s.active.cash,1000000+8000000*factor-5600000);assert.equal(s.active.assets.properties.length,0);assert.equal(s.active.liabilities.mortgage.length,0);assert.equal(s.active.debtTotal,0);
}
for(const id of ['characters-003','characters-009','characters-010','characters-011']){for(const card of cards.filter(c=>/失業/.test((c.effective.title||'')+(c.effective.effect||'')))){const s=session(card.cardId,[1],id),salary=s.active.salaryIncome,cash=s.active.cash;assert.equal(s.active.employment.industry,'無產業');if(s.isMarketCard())s.beginMarket();else s.apply();assert.equal(s.active.salaryIncome,salary);assert.equal(s.active.cash,cash);assert.notEqual(s.active.employment.unemployed,true);}const s=session('stock-news-029',[1],id);s.active.employment.industry='金融';const r=new E.play.Session(cards,B,()=>0,s.state);assert.equal(r.active.employment.industry,'無產業');}
console.log('PASS: every event dice card, all investment outcomes, 36 two-dice and 216 three-dice combinations, funding, reload/idempotence, transfer, debt, four industry-free roles');
module.exports={session,E,B,cards};
