'use strict';
const assert=require('node:assert/strict');
global.window=global;require('../data/game-data-bundle.js');
const E=require('../data/game-engine.js'),B=require('../js/board.js'),AI=require('../js/ai.js');
const cards=GAME_SOURCE_BUNDLE.sources.map(c=>E.derive(c));
function session(configure=true){const s=new E.play.Session(JSON.parse(JSON.stringify(cards)),B,()=>0);s.start('真人','characters-009');for(const p of s.state.players){p.cash=1000000;p.monthlySalary=38000;p.isStudent=false;p.isEmployed=true;E.play.calculate(p);}if(configure)for(const kind of ['stocks','futures','bondsFunds','meeting','risk'])s.setEligibleTraders(kind,[0,1,2,3]);return s;}
function open(s,id='futures-market-001',trigger=0){s.state.phase='resolving';s.state.turn=trigger;s.state.pending={kind:'card',cardId:id,tileId:'taiwan-11'};return s.beginMarket();}
function close(s){while(s.marketPhase){if(s.trader)s.completeMarket();else s.acknowledgeMarket();}}
function quoteCard(s,price){const c=s.byId.get('futures-market-001');c.effective.fields={生絲:price,黃豆:23000};c.effective.effect='';return c;}
function unchanged(s,fn){const before=JSON.stringify(s.state);assert.throws(fn);assert.equal(JSON.stringify(s.state),before);}
const results=[];
function test(name,fn){fn();results.push(name);console.log('PASS '+name);}
test('Explicit card prohibition preserves global updates without trading',()=>{const s=session(false);s.byId.get('futures-market-001').eligibleTraders=[];const m=open(s,'futures-market-001',2);assert.equal(s.trader,null);assert.deepEqual(m.eligibleTraders,[]);assert.equal(s.state.marketState.futures.黃豆,23000);unchanged(s,()=>s.buyMarket('黃豆',1));s.acknowledgeMarket();assert.equal(s.state.turn,2);});
test('Explicit card participant subset is separate from trigger and affected participants',()=>{const s=session(false);s.byId.get('futures-market-001').eligibleTraders=[1,3];open(s,'futures-market-001',2);assert.deepEqual(s.marketPhase.marketParticipants,[0,1,2,3]);assert.deepEqual(s.marketPhase.eligibleTraders,[1,3]);assert.equal(s.trader.id,1);unchanged(s,()=>s.executeMarket('黃豆',1,'buy',2,s.marketPhase.id));close(s);});
test('Student, unemployed, zero salary blocked independently of zone or drawer',()=>{const s=session();s.state.players[0].isStudent=true;s.state.players[1].monthlySalary=0;s.state.players[2].isEmployed=false;s.state.players[3].zone='taiwan';open(s,'futures-market-001',0);assert.deepEqual(s.marketPhase.eligibleTraders,[0,1,2,3]);assert.equal(s.canTradeFutures(s.state.players[0]),false);assert.equal(s.canTradeFutures(s.state.players[3]),true);s.trader.isStudent=true;assert.equal(s.tradeQuote('黃豆',1).allowed,false);});
test('Margin 3000, combined salary quota floor, no short selling, counter survives reload',()=>{const s=session();open(s);const item=s.marketItems()[0];s.buyMarket(item.name,2);assert.equal(s.trader.cash,994000);const a=s.trader.assets.futures[0];assert.equal(a.entryPrice,item.currentMarketPrice);assert.equal(a.margin,6000);assert.equal(a.quantity,2);assert.equal(a.sourceMarketCardId,'futures-market-001');s.sellMarket(item.name,1);assert.equal(s.trader.cash,994000);assert.equal(s.futuresQuota().remaining,1);s.buyMarket(s.marketItems()[1].name,1);unchanged(s,()=>s.buyMarket(item.name,1));const restored=new E.play.Session(cards,B,()=>0,s.state);assert.equal(restored.futuresQuota().used,3);assert.equal(restored.futuresQuota().remaining,0);unchanged(restored,()=>restored.sellMarket(item.name,2));unchanged(restored,()=>restored.buyMarket(item.name,1,1));close(restored);open(restored);assert.equal(restored.futuresQuota().used,0);});
test('13000 -> 10000 liquidates all holders, including nontraders and students, exactly once',()=>{const s=session();quoteCard(s,13000);open(s);for(let i=0;i<4;i++){s.buyMarket('生絲',1);s.completeMarket();}s.state.players[1].isStudent=true;s.byId.get('futures-market-001').eligibleTraders=[];quoteCard(s,10000);const m=open(s,'futures-market-001',2);assert.equal(m.items[0].previousMarketPrice,13000);assert.equal(s.state.marketState.futures.生絲,10000);for(const p of s.state.players){assert.equal(p.assets.futures.length,0);assert.equal(p.cash,994000);}assert.equal(m.effectResults.filter(r=>r.type==='FUTURES_LIQUIDATION').length,4);const before=JSON.stringify(s.state);s.beginMarket();assert.equal(JSON.stringify(s.state),before);const restored=new E.play.Session(s.cards,B,()=>0,s.state);restored.beginMarket();assert.equal(restored.state.players[0].cash,994000);});
test('Loss below threshold stays open; gains never liquidate; close margin + spread - fee',()=>{const s=session();quoteCard(s,13000);open(s);s.buyMarket('生絲',3);close(s);quoteCard(s,10001);open(s);assert.equal(s.trader.assets.futures[0].quantity,3);assert.equal(s.trader.assets.futures[0].value,3);close(s);quoteCard(s,23000);open(s);assert.equal(s.trader.assets.futures[0].quantity,3);const q=s.tradeQuote('生絲',2,'sell');assert.equal(q.pnl,20000);assert.equal(q.margin,6000);assert.equal(q.fee,6000);assert.equal(q.proceeds,20000);assert.equal(q.netProfit,14000);s.sellMarket('生絲',2);assert.equal(s.trader.cash,1011000);assert.equal(s.trader.assets.futures[0].quantity,1);assert.equal(s.trader.assets.futures[0].margin,3000);});
test('Multiple entry lots require selection; partial close preserves remaining basis',()=>{const s=session();quoteCard(s,13000);open(s);s.buyMarket('生絲',1);close(s);quoteCard(s,14000);open(s);s.buyMarket('生絲',2);assert.equal(s.tradeQuote('生絲',1,'sell').allowed,false);const lot=s.trader.assets.futures[1],q=s.executeMarket('生絲',1,'sell',s.trader.id,s.marketPhase.id,lot.id);assert.equal(q.entryPrice,14000);assert.equal(q.amount,0);assert.equal(s.trader.assets.futures[0].entryPrice,13000);assert.equal(s.trader.assets.futures[1].quantity,1);assert.equal(s.futuresQuota().used,2);});
test('Legacy full-price futures do not silently convert/refund or crash new quotes',()=>{const s=session();s.active.assets.futures.push({id:'old',cardId:'futures-market-001',name:'生絲',units:1,cost:13000,value:13000,income:0,operatingExpense:0});quoteCard(s,10000);open(s);assert.equal(s.active.cash,1000000);assert.equal(s.active.assets.futures[0].cost,13000);assert.match(s.marketPhase.issues.join(' '),/舊制持倉/);assert.equal(s.tradeQuote('生絲',1,'sell').allowed,false);s.buyMarket('生絲',1);const id=s.trader.assets.futures.at(-1).id;s.executeMarket('生絲',1,'sell',s.trader.id,s.marketPhase.id,id);assert.equal(s.trader.assets.futures.length,1);assert.equal(s.trader.assets.futures[0].id,'old');assert.equal(s.trader.assets.futures[0].cost,13000);});
test('Risk exemption <=300000 prevents followup quote and forced purchases',()=>{for(const cash of [0,299999,300000]){const s=session();s.active.cash=cash;const c=s.cards.find(c=>c.category==='詭譎市場');const m=open(s,c.cardId);assert.equal(m.exempt,true);assert.equal(m.items.length,0);assert.equal(m.effectResults.length,0);assert.equal(s.active.cash,cash);}});
test('Board risk exemption produces no DRAW and no market stage',()=>{const s=session(),index=B.zone('taiwan').findIndex(t=>t.cardPool?.gameModule==='期貨系統');assert.ok(index>0);s.active.position=index-1;s.active.cash=300000;s.cards=s.cards.filter(c=>c.category==='詭譎市場');s.roll();assert.equal(s.state.pending.kind,'rest');assert.equal(s.marketPhase,null);assert.ok(s.state.events.some(e=>e.code==='RISK_EXEMPT'));assert.ok(!s.state.events.some(e=>e.code==='DRAW'));});
test('Risk stocks force only trigger; futures ambiguity explicit while global quote updates',()=>{for(const c of session().cards.filter(c=>c.category==='詭譎市場')){const s=session(),m=open(s,c.cardId,2);assert.ok(m.items.length);assert.ok(m.effectResults.filter(r=>r.type==='FORCED_PURCHASE').every(r=>r.playerId===2));assert.ok(s.state.players.filter(p=>p.id!==2).every(p=>p.cash===1000000));if(m.items[0].asset==='futures'){assert.ok(s.state.marketState.futures);assert.match(m.issues.join(' '),/月薪口數上限/);}else assert.ok(m.effectResults.some(r=>r.type==='FORCED_PURCHASE'));s.validate();}});
test('Cash stock lots and fee; bonds zero fee; funds 3000 per unit on both sides',()=>{const s=session();const c=s.byId.get('stock-news-001');c.effective.fields={水泥:9};open(s,'stock-news-001');assert.equal(s.tradeQuote('水泥',1).cost,10000);s.buyMarket('水泥',2);assert.equal(s.trader.assets.stocks[0].units,2000);assert.equal(s.tradeQuote('水泥',1,'sell').proceeds,8000);s.sellMarket('水泥',1);assert.equal(s.trader.cash,988000);close(s);open(s,'bond-fund-002');const bond=s.tradeQuote('政府公債',2);assert.equal(bond.fee,0);s.buyMarket('政府公債',2);assert.equal(s.tradeQuote('政府公債',1,'sell').fee,0);const fund=s.tradeQuote('東歐基金',2);assert.equal(fund.fee,6000);s.buyMarket('東歐基金',2);assert.equal(s.tradeQuote('東歐基金',1,'sell').fee,3000);assert.equal(s.tradeQuote('新興市場',1).allowed,false);});
test('Stock, futures, bonds each support configured human + three AI without turn-owner mutation',()=>{for(const id of ['stock-news-001','futures-market-001','bond-fund-002']){const s=session();open(s,id,2);const trace=[];while(s.marketPhase){const p=s.trader,actions=p.personality==='human'?[{name:s.marketItems()[0].name,units:1,side:'buy'}]:AI.decideMarket(s);for(const a of actions)s.executeMarket(a.name,a.units,a.side,p.id,s.marketPhase.id,a.holdingId);trace.push({id:p.id,actions});s.completeMarket();}assert.deepEqual(trace.map(x=>x.id),[0,1,2,3]);assert.ok(trace.slice(1).some(x=>x.actions.length));assert.equal(s.state.turn,2);}});
test('All 96 market cards have split scopes and safe unconfigured completion',()=>{const base=session(false);let count=0;for(const c of base.cards.filter(c=>c.eventType==='MARKET_EVENT')){const s=session(false);open(s,c.cardId,1);assert.ok(c.eventScopes.includes('GLOBAL_MARKET_UPDATE'));if(c.category==='詭譎市場')assert.ok(c.eventScopes.includes('CURRENT_PLAYER_EVENT'));s.validate();close(s);assert.equal(s.state.phase,'done');count++;}assert.equal(count,96);});
test('Player expense affects trigger only; no market phase',()=>{const s=session();s.state.turn=2;s.state.phase='resolving';s.state.pending={kind:'card',cardId:'daily-life-009'};assert.equal(s.isMarketCard(),false);s.apply();assert.deepEqual(s.state.players.map(p=>p.cash),[1000000,1000000,999000,1000000]);});
test('Old pending market restores existing eligible-player fallback without replay',()=>{const s=session();open(s);s.buyMarket('黃豆',1);delete s.marketPhase.version;delete s.marketPhase.eligibleTraders;const restored=new E.play.Session(cards,B,()=>0,s.state);assert.deepEqual(restored.marketPhase.eligibleTraders,[0,1,2,3]);assert.equal(restored.state.players[0].cash,997000);restored.beginMarket();assert.equal(restored.state.players[0].cash,997000);});
console.log(JSON.stringify({passed:true,groups:results.length,results}));
module.exports={session,open,close,cards,E,B,results};
